<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXZLJbkL\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXZLJbkL/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXZLJbkL.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXZLJbkL\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXZLJbkL\App_KernelDevDebugContainer([
    'container.build_hash' => 'XZLJbkL',
    'container.build_id' => 'ac6febd4',
    'container.build_time' => 1657014964,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXZLJbkL');
